name: Save Shard Price History
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  save_history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios firebase-admin
      - name: Run script to save shard history
        run: node ./fetch-shards.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
