name: Track Ended Auctions

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  track_auctions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios firebase-admin

      - name: Run script to track ended auctions
        run: node ./fetch-ended-auctions.js
        env:
          FIREBASE_CONFIG_AUCTIONS: ${{ secrets.FIREBASE_CONFIG_AUCTIONS }}

      # NEU: Dieser Schritt lädt die neue JSON-Datei ins Repository hoch
      - name: Commit and push auction history file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add auction-history.json
          # Commit nur, wenn es Änderungen gibt
          git diff --staged --quiet || git commit -m "Update auction-history.json"
          git push
